apiVersion: batch/v1
kind: Job
metadata:
  name: chaos-oom-toggle
  namespace: incident-copilot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.30
        command: ["/bin/sh","-lc"]
        args:
          - |
            set -e
            echo "Triggering OOM by lowering memory limit to 64Mi"
            kubectl -n demo patch deploy/oom-demo -p '{"spec":{"template":{"spec":{"containers":[{"name":"stress","resources":{"limits":{"memory":"64Mi"}}}]}}}}'
            sleep 10
            echo "Restoring to 256Mi"
            kubectl -n demo patch deploy/oom-demo -p '{"spec":{"template":{"spec":{"containers":[{"name":"stress","resources":{"limits":{"memory":"256Mi"}}}]}}}}'