apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agent-collector
  namespace: incident-copilot
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: agent-collector
  template:
    metadata: 
      labels: 
        app: agent-collector
    spec:
      serviceAccountName: agent-collector
      containers:
      - name: app
        image: docker.io/petitsinge/incident-copilot-agent-collector:latest
        ports: 
        - containerPort: 8000
        env:
        - name: CLUSTER_NAME
          value: "incident-copilot"
        - name: WORKSPACE
          value: "TiM8-Local"
        envFrom:
        - secretRef: 
            name: copilot-secrets
        - configMapRef: 
            name: copilot-config
---
apiVersion: v1
kind: Service
metadata: 
  name: agent-collector
  namespace: incident-copilot
spec:
  selector: 
    app: agent-collector
  ports: 
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-collector
  namespace: incident-copilot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-collector
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-collector
subjects:
- kind: ServiceAccount
  name: agent-collector
  namespace: incident-copilot