apiVersion: v1
kind: Secret
metadata: 
  name: copilot-secrets
  namespace: incident-copilot
type: Opaque
stringData:
  OPENAI_API_KEY: "sk-..."
  TIDB_HOST: "tidb-host"
  TIDB_PORT: "4000"
  TIDB_USER: "user"
  TIDB_PASSWORD: "password"
  TIDB_DB: "incidentdb"
  SLACK_WEBHOOK: ""