apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: oom-demo
  template:
    metadata:
      labels: 
        app: oom-demo
    spec:
      containers:
      - name: stress
        image: polinux/stress
        args: ["--vm","1","--vm-bytes","150Mi","--vm-hang","1"]
        resources:
          limits: 
            memory: "128Mi"
          requests: 
            memory: "64Mi"
---
apiVersion: v1
kind: Namespace
metadata: 
  name: demo